server.port=8790
spring.application.name=m2o-sink-connector-dev

management.endpoint.health.enabled=true
management.health.defaults.enabled=true

spring.boot.admin.client.url=http://localhost:8080
management.endpoints.web.exposure.include=*

kafka.bootstrap-servers=localhost:9999
m2o.sink.environment=Global
m2o.source.topicbase=requestTopic

#IBM MQ Queue Manager Details
ibm:
  mq:
    queueManager: "QM1"
    channel: "DEV.ADMIN.SVRCONN"
    connName: "localhost(1414)"
    user: "admin"
    password: "passw0rd"
    #message.pooling.rate: 100

m2o.sink.queue.staging=true
m2o.sink.queue.staging.suffix=.STG

#Executor Thread Configurations
pool.size=10
maxpool.size=50

#logging.level.root=DEBUG