server.port: 8790

spring:
  application:
    name: sink-connector
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance.metadata.tags.environment: DEV

management:
  endpoints:
    actuator.enabled: true
    health.enabled: true
    service-registry.enabled: true
    web.exposure.include: "*"
  #   logfile.external-file: /tmp/m2o-source-connector.log
  #  health.defaults.enabled: true

#### KAFKA CONFIGS#######
state.dir: "/Users/magnet/Apps/kafka_2.13-2.6.0/kafka-state"
kafka.bootstrap-servers: localhost:9092

m2o:
  sink:
    sourceTopic: responseTopicAccInfoRetail
    destinationQueue: service.accounting.response.retail

#IBM MQ Queue Manager Details
ibm:
  mq:
    queueManager: "QM1"
    channel: "DEV.ADMIN.SVRCONN"
    connName: "localhost(1414)"
    user: "admin"
    password: "passw0rd"
    #message.pooling.rate: 100


  #Executor Thread Configurations
pool.size: 10
maxpool.size: 50

#logging.level.root=DEBUG